### ISSUE TITLE
Creating a Camera Application

### ISSUE THREAD

**Issue by trickring** [trickring/DJISampleDemo#4]
## Overview

- Using capture and video of a camera of aircraft.

## Steps

1. Installing Mobile SDK and UX Widget SDK.
2. Activating aircraft.
3. UIButton of taking capture and video. also, stop taking video.
4. UISegumentedControl of switching capture and video.
4. Setting button action

## Links

- [Creating a Camera Application \- DJI Mobile SDK Documentation](https://developer.dji.com/mobile-sdk/documentation/ios-tutorials/index.html)

**Comment by matsushitak** [comment]
I committed.
